### PR TITLE
feat: make this repo a copier template

### LINKED ISSUE #9: Turn metarepo into a copier template
To seamlessly set up a *dev metarepo*, this process should be migrated to a cookiecutter template.

### PR DESCRIPTION
**Pull request by aelskens**
BREAKING CHANGE: the metarepo is now a copier template.

### CODE REVIEW

**Comment by echarles** [comment]
Thx  @aelskens 

In the meantime, https://github.com/datalayer/metarepo/pull/15 has been merged to address https://github.com/datalayer/metarepo/issues/14

2 impacts on this PR:

1. It needs to be rebased
2. The list of javascript packages needs to be created based on the given repositories. This implies that the user needs to be prompted with the repositories, as well with their associated javascript package.

**Comment by echarles** [comment]
Just pushed more in https://github.com/datalayer/metarepo/commit/d4c194642f8cf444df018e66fd9b40caeeb1c352

Current main branch is now fully usable

```
➤ YN0000: Done with warnings in 3m 39s
(datalayer) echarles@echarles:~/Desktop/metarepo$ yarn build
lerna notice cli v8.0.2
 
    ✔  @datalayer/jupyter-react:build (31s)
    ✔  @datalayer/jupyter-iam:build (28s)
    ✔  @datalayer/jupyter-content:build (28s)
    ✔  @datalayer/jupyter-environments:build (35s)
    ✔  @datalayer/jupyterpool:build (26s)
    ✔  @datalayer/jupyter-ui:build (36s)
    ✔  @datalayer/jupyter-kernels:build (35s)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Successfully ran target build for 7 projects (4m)

```

**Comment by echarles** [comment]
> The list of javascript packages needs to be created based on the given repositories. This implies that the user needs to be prompted with the repositories, as well with their associated javascript package.

With the last push, this is no more required (no need to add the javavascript packages), so simpler to update this PR

**Comment by aelskens** [comment]
With this commit, I think we are ready to merge the PR @echarles and therefore close #9.

**Comment by echarles** [comment]
@aelskens the PR is still showing clonflcts and can not be merged as-is

Screenshot from 2024-01-18 04-37-47

**Review by echarles — APPROVED** [review]
LGTM Awesome @aelskens

**Comment by echarles** [comment]
Awesome @aelskens

**Pull request merged**
